### ISSUE TITLE
Convert CDK dependencies to peerDependencies to help avoid version conflicts

### ISSUE THREAD

**Issue by igilham** [eladb/cdk-watchful#17]
This library does not keep pace with new versions of CDK so it can quickly lead to version conflicts.

Changing the CDK dependencies to peerDependencies should help to minimise the frustration of managing potentially conflicting versions of everything.

**Comment by ali-habibzadeh** [comment]
True, I have never actually managed to deploy a stack with this without getting weird errors like not liking scope Construct as the right type for `this` or EC2 conflicts.

**Comment by bobmoff** [comment]
so, i need to downgrade cdk to match the level of this package to use it ?

**Comment by igilham** [comment]
Right now, the easiest way to use this library is to copy the code to your own project and make any adjustments you need to support the same CDK version etc.

This is not without value, but reuse by dependency management would be more convenient if it can be done safely without breaking the CDK dependency all the time.

**Comment by eladb** [comment]
Done
