### ISSUE TITLE
Cannot read property 'readCapacityUnits' of undefined

### ISSUE THREAD

**Issue by 9tontruck** [eladb/cdk-watchful#2]
https://github.com/eladb/cdk-watchful/blob/f43380c2e871ffd4e55a2cdce190a23d4c6de0aa/lib/dynamodb.ts#L52

Throwing "Cannot read property 'readCapacityUnits' of undefined"

**Comment by seawatts** [comment]
Also having this same issue.

**Comment by 9tontruck** [comment]
> Also having this same issue.

If you are Amazonian, this might help
https://code.amazon.com/packages/ImageMetadataLambda/blobs/mainline/--/src/lib/resources/dynamodb-alarms.ts

**Comment by seawatts** [comment]
The problem for me was that my billing mode for my table was set to

```
  billingMode: BillingMode.PAY_PER_REQUEST,
```

If you set it to `BillingMode.PROVISIONED` then this works.

You can also turn on auto scaling with this:

```
myTable.autoScaleReadCapacity({ minCapacity: 50, maxCapacity: 100 });
```

**Comment by igilham** [comment]
Perhaps it would be better if watchful emitted a warning for tables using on-demand mode and skip creating the resources for them. Or maybe there are some metrics worth monitoring on these tables?

**Comment by nzamosenchuk** [comment]
This issue actually blocks the most beautiful and most customer-obsessed feature of Watchful - watch scope.
Warning indeed would be sufficient.
